### PR TITLE
Support deploy cilium related services

### PR DESCRIPTION
**Pull request by mrproliu**

### CODE REVIEW

**Comment by wu-sheng** [comment]
https://skywalking.apache.org/docs/skywalking-showcase/next/readme/#features

I think this table is not updated, and is Cilium k8s only?

**Comment by mrproliu** [comment]
The documentation has been updated, and the Cilium is k8s only.

**Comment by wu-sheng** [comment]
Which parts in the docs are mentiong scopes? K8s or docker compose or both?

**Comment by mrproliu** [comment]
> Which parts in the docs are mentiong scopes? K8s or docker compose or both?

Sorry, I forget to adding note about this.

**Pull request merged**
