### PR TITLE
Add virtual MQ showcase 

### PR DESCRIPTION
**Pull request by pg-yang**
172.31.0.2:61616 is activemq server

image

image

image

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Hi @pg-yang , can you also share the related traces? And please also update the topology in the doc.

The resource cost looks reasonable to me, it adds <= 0.1C/256M.

**Comment by pg-yang** [comment]
image

The traces of MQ is not continued .

And I only checked docker deployment as  i don't have enough resource to run k8s on  my  PC .

**Comment by wu-sheng** [comment]
It seems the producer/consumer continues, is there an async from HTTP request to sending a message?

**Comment by pg-yang** [comment]
I  try create a controller to send MQ  message  , but  it was truncated too . it seems the reason of  gateway plugin .

**Comment by wu-sheng** [comment]
Oh, Gateway is not a good place to do that. Spring Gateway has a lot of async. I am not sure whether you triggered something. It is better to put this logic in a simple SpringMVC Controller.

**Comment by pg-yang** [comment]
Yes , I have to  create a new service  with MQ producer .

**Comment by wu-sheng** [comment]
Isn't an existing Java application? Besides the gateway? If there is one, we could build a producer and consumer for the same service.

**Comment by pg-yang** [comment]
Only  songs is java application  except gateway  . If  build producer and consumer  to songs  , the traces would be loop :

```mermaid
%% please read this doc in our official website, otherwise the graph is not correctly rendered.
graph LR;
songs --> acvivemq

acvivemq --> songs 
```

**Comment by wu-sheng** [comment]
I think it is fine to find a loop with mutiple endpoints. After all, we are just showing the capability

**Comment by pg-yang** [comment]
image

image

image

The doc 

```mermaid
%% please read this doc in our official website, otherwise the graph is not correctly rendered.
graph LR;
  loadgen[load generator] --> ui("UI (React)") --> Traffic1("HTTP Request for backend serv") -->  apisix("APISIX as UI container")
 --> app("app server (NodeJS)") --> gateway("gateway (Spring)");
  ui("UI (React)") --> Traffic2("HTTP Request for UI codes") --> apisix("APISIX with  UI container")
  gateway --> songs("songs (Spring)") & rcmd("recommendations (Python)");
  songs --> activeMQ
  activeMQ --> songs
  rcmd --> songs;
  songs --> db("database (H2)");
```

**Comment by wu-sheng** [comment]
@kezhenxu94 PTAL. BTW, could you revert the last change on the demo installer? As https://github.com/apache/skywalking/pull/9954 had been merged, we should test whether it is fixed.

**Pull request merged**
