### PR TITLE
Add virtual cache show case

### PR DESCRIPTION
**Pull request by pg-yang**
image

image

Close https://github.com/apache/skywalking/issues/9556

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]

**Comment by wu-sheng** [comment]
@pg-yang @kezhenxu94 I can see the new `virtual cache` menu, but don't see any data in it. 

Please recheck. The songs app's traces don't include guava access.

**Comment by kezhenxu94** [comment]
> @pg-yang @kezhenxu94 I can see the new `virtual cache` menu, but don't see any data in it. 
> 
> 
> 
> Please recheck. The songs app's traces don't include guava access.

This is not deployed yet. Just clicked to redeploy the showcase.

**Comment by wu-sheng** [comment]
But I see the OAP version has been upgraded, are they separated?

**Comment by pg-yang** [comment]
The endpoint `GET:/songs` exist .   It look  seems guava cache is  inactive . 
Notice  , I updated Dockerfile to activate guava cache .

**Comment by pg-yang** [comment]
Thanks Zhenxu , k8s use agentless injector  , docker use Dockerfile I updated .

**Pull request merged**
