### PR TITLE
fix rocketMQ NAMESRV_ADDR

### PR DESCRIPTION
**Pull request by wankai123**
@peachisai previous `NAMESRV_ADDR` is incorrect.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@peachisai You should run this deployment locally next time to make sure it works as expected.

**Comment by peachisai** [comment]
Sorry ,But it is stranged, localhost is ok in my local environment。

**Comment by wu-sheng** [comment]
> Sorry ,But it is stranged, localhost is ok in my local environment。

Please try KinD as local k8s env. Minikube sometimes is not that good AFAIK.

**Comment by peachisai** [comment]
> > Sorry ,But it is stranged, localhost is ok in my local environment。
> 
> Please try KinD as local k8s env. Minikube sometimes is not that good AFAIK.

Ok ,I will try KinD

**Pull request merged**
