### PR TITLE
Switch to otlp exporter for all OTEL collector

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
As this is proved working, let's update the example yaml in the main repo doc, update all to otlp.

**Comment by kezhenxu94** [comment]
> As this is proved working, let's update the example yaml in the main repo doc, update all to otlp.

Which part do you mean? I think we don't have "example yaml" in main repo doc,

**Comment by wu-sheng** [comment]
I remember we have, as those configurations in e2e testing, and referred from setup doc as examples.

**Comment by kezhenxu94** [comment]
> I remember we have, as those configurations in e2e testing, and referred from setup doc as examples.

OK, if you mean configs in E2E, then we have those

**Pull request merged**
